# vim: ts=2:sw=2:sts=2:et:ft=yaml
# -*- mode: yaml; yaml-indent-offset: 2; indent-tabs-mode: nil; -*-
---
# GNU General Public License v3.0+
# SPDX-License-Identifier: GPL-3.0-or-later
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
#
# Copyright (c) 2025 oØ.o (@o0-o)
#
# This file is part of the o0_o.utils Ansible Collection.

name: CI

'on':
  pull_request:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build Collection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ansible-core
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core

      - name: Install linters
        run: |
          pip install yamllint black flake8

      - name: Run black
        run: black --check --diff --color .

      - name: Run flake8
        run: flake8 --count --show-source --statistics .

      - name: Run yamllint
        run: yamllint -f parsable .

      - name: Run Quick Sanity Test
        run: ansible-test sanity

      - name: Build collection
        run: ansible-galaxy collection build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ansible-collection-tarball
          path: '*.tar.gz'

  tests:
    name: Run ansible-test ${{ matrix.test_type }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        test_type: [sanity, units, integration]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download built collection
        uses: actions/download-artifact@v4
        with:
          name: ansible-collection-tarball
          path: ./build

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install ansible-core
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core

      - name: Install built collection (with dependencies)
        run: |
          ansible-galaxy collection install ./build/o0_o-utils-*.tar.gz \
            --force -p ~/.ansible/collections -vvv

      - name: Run ansible-test ${{ matrix.test_type }}
        run: |
          cd ~/.ansible/collections/ansible_collections/o0_o/utils
          ansible-test ${{ matrix.test_type }} --docker -v


  publish:
    name: Publish to Galaxy
    runs-on: ubuntu-latest
    needs: tests
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: ansible-collection-tarball

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ansible-core
        run: |
          pip install --upgrade pip
          pip install ansible-core

      - name: Publish to Galaxy
        run: >-
          ansible-galaxy collection publish *.tar.gz
          --token ${{ secrets.GALAXY_API_KEY }}
